---
title: "lab7"
format: github_document
---

```{r}
library(tidyverse)
library(knitr)
library(nycflights13) # install.packages("nycflights13")
flights |> head() |> kable()
View(flights)
View(airports)
```

### Q1

```{r}
avg_delay_des<-flights |> 
  group_by(dest) |> 
  summarise(delay=mean(arr_delay,na.rm=TRUE))

avg_delay_des |> 
  left_join(airports, c("dest" = "faa")) |> 
  ggplot(aes(lon, lat)) +
    borders("state") +
    geom_point() +
    coord_quickmap()
```

### Q2

```{r}
#planes
age_delay<-planes |> 
  inner_join(flights,by="tailnum",suffix = c("_flight", "_plane")) |> mutate(
    age = year_flight - year_plane
  ) |>  filter(!is.na(age)) |>
  group_by(age) |>
  summarise(
    avg_dep_delay = mean(dep_delay, na.rm = TRUE),
    avg_arr_delay = mean(arr_delay, na.rm = TRUE),
    n = n()
  )

ggplot(age_delay,aes(x=age,y=avg_dep_delay))+
  geom_point()
ggplot(age_delay,aes(x=age,y=avg_arr_delay))+
  geom_point()
```

### Q3

```{r}
#View(weather)
wea_delay<-flights |> 
  inner_join(weather,
             by=c("origin","year","month","day","hour")
             ) |> 
  group_by(precip) |> 
   summarise(delay = mean(dep_delay, na.rm = TRUE))

wea_delay |> 
  ggplot(aes(x = precip, y = delay)) +
  geom_line() + 
  geom_point()
```

## **Exercise 2: Baby names**

```{r}
library(babynames) # install.packages("babynames")
library(dplyr)

babynames |> head() |> kable()
```

### Q1

```{r}
top6_names <- babynames  |> 
  group_by(sex, name)  |> 
  summarize(total = sum(n), .groups = "drop") |> 
  group_by(sex) |> 
  slice_max(order_by = total, n = 6) 
top6_names <- babynames|> 
  semi_join(top6_names, by = c("sex", "name"))

top6_names |> ggplot(aes(x = year, y = n, color = name)) +
  geom_line() +
  facet_wrap(~ sex, scales = "free_y")
```

Q2

```{r}
new_names <- babynames |> 
  mutate(period = ifelse(year < 2010, "before_2010", "after_2010"))  |> 
  group_by(name, period)  |> 
  summarize(total = sum(n), .groups = "drop") |> 
  pivot_wider(names_from = period, values_from = total, values_fill = 0) |> 
  filter(before_2010 == 0, after_2010 > 1000)

new_names

```

Q3

```{r}
unisex_names <- babynames  |> 
  group_by(name, sex)  |> 
  summarize(total = sum(n), .groups = "drop") |> 
  pivot_wider(names_from = sex, values_from = total, values_fill = 0)  |> 
  mutate(
    total_all = F + M,
    prop_girl = F / total_all
  )  |> 
  filter(prop_girl >= 0.1, prop_girl <= 0.9)  |> 
    slice_max(order_by = total_all, n = 12)

unisex_data <- babynames  |> 
  semi_join(unisex_names, by = "name")  |> 
  group_by(year, name)  |> 
  summarize(prop_girl = sum(n[sex == "F"]) / sum(n), .groups = "drop")

unisex_data |> ggplot(aes(x = year, y = prop_girl, color = name)) +
  geom_line()
```
